# Generated by Django 5.1.1 on 2024-10-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Borrowing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("borrow_date", models.DateField(auto_now_add=True)),
                ("expected_return", models.DateField()),
                ("actual_return", models.DateField(blank=True, null=True)),
                ("book_id", models.PositiveIntegerField()),
                ("user_id", models.PositiveIntegerField()),
            ],
        ),
    ]
